# Generated by Django 4.2.16 on 2024-11-08 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_alter_callrecord_call_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 8, 17, 56, 15, 779980, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 8, 17, 56, 24, 13085, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
